### ISSUE TITLE
HazardRecognizerTest fails in CI

### ISSUE THREAD

**Issue by stephenneuendorffer** [Xilinx/llvm-aie#13]
This is concerning, I never saw those tests failing locally. This is essentially just verifying the intersection of two bitsets. It then seems that the bitset inside `HR` at cycle `-2` isn't properly set by `HR.emit(1, -2, /*SlotSet=*/0b01);`

_Originally posted by @gbossu in https://github.com/Xilinx/llvm-aie/pull/12#discussion_r1582617424_

**Comment by martien-de-jong** [comment]
Ok. Bottom line is that the AIETests unittest executable combines an AIE1 and an AIE2 hazardrecognizer, and there's an ugly static implementation pointer that get's trashed to the wrong version. The failure is dependent on the number of batches AIETests is split in; As such, splitting in batches is a bad thing, if only since running all of AIETests takes 16 ms.

The test changed nature when we started to use the format interface to test conflicts in FuncUnitWrapper; before that, they were separately tested in AIEBundle.

**Comment by gbossu** [comment]
Fixed in 3c7502ced68e09b8bed6d350ee7aadb28c3860d0, closing.
